#!/bin/sh

deps='
dvv/simple/src:simple
Modernizr/Modernizr/modernizr.js:COPY
douglascrockford/JSON-js/json2.js:BUNDLE
documentcloud/underscore/underscore.js:BUNDLE
dvv/simple/lib/object.js:BUNDLE
dvv/simple/lib/rql.js:BUNDLE
dvv/simple/lib/validate.js:BUNDLE
documentcloud/backbone/backbone.js:BUNDLE
edtsech/underscore.string/lib/underscore.string.js:BUNDLE
dvv/schema2form/index.js:BUNDLE
#3rd-eden/node-useragent/useragent.js:useragent.js
#weaver/node-mail/lib/mail:mail
#miksago/node-websocket-server/lib:ws-server
#learnboost/socket.io-node:io
#
#cloudhead/vows/lib:vows
#dvv/Faker.js:faker
#
dvv/simple-geoip:geoip
#
'

# download dependencies
lib=node_modules
COPY=public/js
BUNDLE=public/js/bundle.js
mkdir -p "$lib"
rm "$BUNDLE"
for dep in $deps; do
	# skip comments
	case "$dep" in
		\#*) continue ;;
	esac
	# parse definition
	path=${dep%:*}
	link=${dep##*:}
	author=${path%%/*}
	path=${path#*/}
	git=${path%%/*}
	# fetch the package
	echo link ${author}\'s $git to $link, path $path
	#continue
	if ! test -d git/${git}; then
		#git clone https://github.com/${author}/${git}.git git/${git}
		mkdir -p git/${git}
		wget -ct3 -q --progress=bar --no-check-certificate http://nodeload.github.com/${author}/${git}/tarball/master -O- | tar -xzf- --strip 1 -C git/${git}
		cd git/${git}
		#if test -f Makefile; then
		#	make
		#fi
		if test -f wscript; then
			node-waf configure build
		fi
		cd ../..
	fi
	# symlink entry point
	if test "Q$link" = 'QBUNDLE'; then
		cat "git/$path" >> "$BUNDLE"
	elif test "Q$link" = 'QCOPY'; then
		cp "git/$path" "$COPY"
	elif test "Q$link" != 'Q'; then
		test -e "$lib/$link" || ln -s "../git/$path" "$lib/$link"
	fi
done

exit 0
# minify client-side scripts

cat \
	$jslib/json2.js \
	$jslib/underscore.js \
	$jslib/underscore.string.js \
	$jslib/backbone.js \
	public/js/jquery.textchange.min.js \
	$jslib/schema2form.js \
	\
> public/js/bundle.js
#| build/jsmin > bundle.js

#	$jslib/jquery.tokeninput.js

#	$jslib/modernizr.js
