#!/bin/sh

deps='
dvv/simple/src:simple
#cloudhead/eyes.js/lib/eyes.js:eyes.js
documentcloud/underscore/underscore.js:../js/underscore.js
documentcloud/underscore/underscore.js:../../public/test/underscore.js
edtsech/underscore.string/lib/underscore.string.js:../js/underscore.string.js
jquery/qunit/qunit:../../public/test/qunit
Modernizr/Modernizr/modernizr.js:../../public/js/modernizr.js
douglascrockford/JSON-js/json2.js:../js/json2.js
documentcloud/backbone/backbone.js:../js/backbone.js
dvv/schema2form/index.js:../js/schema2form.js
#3rd-eden/node-useragent/useragent.js:useragent.js
weaver/node-mail/lib/mail:mail
#miksago/node-websocket-server/lib:ws-server
#learnboost/socket.io-node:io
#
#cloudhead/vows/lib:vows
#dvv/Faker.js:faker
#
#dvv/simple-geoip:geoip
#
'

# download dependencies
lib=node_modules
jslib="$lib/../js"
mkdir -p "$lib" "$jslib"
for dep in $deps; do
	# skip comments
	case "$dep" in
		\#*) continue ;;
	esac
	# parse definition
	path=${dep%:*}
	link=${dep##*:}
	author=${path%%/*}
	path=${path#*/}
	git=${path%%/*}
	# fetch the package
	echo link ${author}\'s $git to $link, path $path
	#continue
	if ! test -d git/${git}; then
		#git clone https://github.com/${author}/${git}.git git/${git}
		mkdir -p git/${git}
		wget -ct3 -q --progress=bar --no-check-certificate http://nodeload.github.com/${author}/${git}/tarball/master -O- | tar -xzf- --strip 1 -C git/${git}
		cd git/${git}
		#if test -f Makefile; then
		#	make
		#fi
		if test -f wscript; then
			node-waf configure build
		fi
		cd ../..
	fi
	# symlink entry point
	if test "Q$link" != 'Q'; then
		test -e "$lib/$link" || ln -s "../git/$path" "$lib/$link"
	fi
done

# minify client-side scripts

cat \
	$jslib/json2.js \
	$jslib/underscore.js \
	$jslib/underscore.string.js \
	$jslib/backbone.js \
	public/js/jquery.textchange.min.js \
	$jslib/schema2form.js \
	\
> public/js/bundle.js
#| build/jsmin > bundle.js

#	$jslib/jquery.tokeninput.js

#	$jslib/modernizr.js
