#!/bin/sh

SERVER=http://localhost:3000
#SERVER=http://localhost
#SERVER=http://localhost:8003
#SERVER=http://localhost:8080

#URI="hit?uid=NF3faYazex&ip=76.99.77.126"
URI=js/main.js
#URI=index.html
#URI="Log?limit(10)"

#http_load -parallel 500 -seconds ${1:-10} /dev/stdin << _EOF

#./http_load -parallel 100 -fetches ${1:-10000} /dev/stdin << _EOF
./http_load -parallel 100 -fetches ${1:-10000} /dev/stdin << _EOF
$SERVER/$URI
_EOF

#./http_load -parallel 500 -fetches ${1:-50000} /dev/stdin << _EOF
#http://archonsoftware.com:3000/hit?uid=NF3faYazex&ip=76.99.77.126
#_EOF
